import type { ObsidianClient } from "./obsidian.js";
import type { HtmlExtractor } from "./extractor.js";
import type { ExtractedContent, Logger } from "./types.js";

/**
 * Crawls the link graph starting from an entrypoint file.
 * Uses BFS traversal to discover all linked files, including
 * those generated by plugins (discovered from rendered HTML).
 */
export class LinkCrawler {
  private client: ObsidianClient;
  private extractor: HtmlExtractor;
  private logger: Logger;

  /** Files that have been visited */
  private visited: Set<string> = new Set();

  /** Queue of files to process */
  private queue: string[] = [];

  /** Extracted content for each file */
  private contents: Map<string, ExtractedContent> = new Map();

  /** All valid file paths in the vault (for link resolution) */
  private vaultFiles: Set<string> = new Set();

  constructor(client: ObsidianClient, extractor: HtmlExtractor, logger: Logger) {
    this.client = client;
    this.extractor = extractor;
    this.logger = logger;
  }

  /**
   * Normalize a file path for consistent comparison
   */
  private normalizePath(path: string): string {
    // Remove leading/trailing slashes and normalize
    let normalized = path.trim().replace(/^\/+|\/+$/g, "");

    // Add .md extension if not present and not an image
    if (!normalized.includes(".")) {
      normalized += ".md";
    }

    return normalized;
  }

  /**
   * Check if a path looks like an image
   */
  private isImagePath(path: string): boolean {
    const imageExtensions = [".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".bmp"];
    const lower = path.toLowerCase();
    return imageExtensions.some((ext) => lower.endsWith(ext));
  }

  /**
   * Resolve a link to a full file path
   * Handles Obsidian's flexible linking (shortest unique path)
   */
  private async resolveLink(link: string, sourcePath: string): Promise<string | null> {
    // Skip external links and anchors
    if (link.startsWith("http://") || link.startsWith("https://") || link.startsWith("#")) {
      return null;
    }

    // Skip images
    if (this.isImagePath(link)) {
      return null;
    }

    // Try to resolve using Obsidian's resolver
    const resolved = await this.client.resolveLinkPath(link, sourcePath);
    if (resolved && resolved.endsWith(".md")) {
      return resolved;
    }

    // Fallback: try to find a matching file in vault
    const normalized = this.normalizePath(link);

    // Direct match
    if (this.vaultFiles.has(normalized)) {
      return normalized;
    }

    // Try finding by basename (shortest path matching)
    const basename = normalized.split("/").pop() || "";
    for (const file of this.vaultFiles) {
      if (file.endsWith(basename) || file.endsWith(`/${basename}`)) {
        return file;
      }
    }

    return null;
  }

  /**
   * Process a single file: extract HTML and discover links
   */
  private async processFile(filePath: string): Promise<string[]> {
    const newLinks: string[] = [];

    try {
      // Extract rendered HTML
      const content = await this.extractor.extract(filePath);
      this.contents.set(filePath, content);

      // Resolve each link found in rendered HTML
      for (const link of content.links) {
        const resolved = await this.resolveLink(link, filePath);
        if (resolved && !this.visited.has(resolved)) {
          newLinks.push(resolved);
        }
      }

      // Also parse raw markdown for links (as backup)
      try {
        const rawContent = await this.client.read(filePath);
        const mdLinks = this.extractor.parseMarkdownLinks(rawContent);
        for (const link of mdLinks) {
          const resolved = await this.resolveLink(link, filePath);
          if (resolved && !this.visited.has(resolved)) {
            newLinks.push(resolved);
          }
        }
      } catch {
        // Raw content read failed, continue with HTML-extracted links
      }
    } catch (error) {
      const err = error as Error;
      this.logger.warn(`Failed to process ${filePath}: ${err.message}`);
    }

    return [...new Set(newLinks)];
  }

  /**
   * Crawl the link graph starting from an entrypoint
   * Returns a map of file paths to their extracted content
   */
  async crawl(entrypoint: string): Promise<Map<string, ExtractedContent>> {
    this.logger.info(`Starting crawl from: ${entrypoint}`);

    // Reset state
    this.visited.clear();
    this.queue = [];
    this.contents.clear();

    // Load all vault files for link resolution
    const allFiles = await this.client.listFiles();
    this.vaultFiles = new Set(allFiles);
    this.logger.verbose(`Found ${this.vaultFiles.size} files in vault`);

    // Normalize and validate entrypoint
    const normalizedEntry = this.normalizePath(entrypoint);

    if (!this.vaultFiles.has(normalizedEntry)) {
      // Try to find by basename
      const basename = normalizedEntry.split("/").pop() || "";
      let found = false;
      for (const file of this.vaultFiles) {
        if (file === normalizedEntry || file.endsWith(`/${basename}`)) {
          this.queue.push(file);
          found = true;
          break;
        }
      }
      if (!found) {
        throw new Error(
          `Entrypoint file not found: ${entrypoint}\nMake sure the file exists in your Obsidian vault.`
        );
      }
    } else {
      this.queue.push(normalizedEntry);
    }

    // BFS traversal
    let processed = 0;
    while (this.queue.length > 0) {
      const filePath = this.queue.shift()!;

      // Skip if already visited
      if (this.visited.has(filePath)) {
        continue;
      }

      this.visited.add(filePath);
      processed++;

      this.logger.verbose(`Processing [${processed}]: ${filePath}`);

      // Process file and discover new links
      const newLinks = await this.processFile(filePath);

      // Add new links to queue
      for (const link of newLinks) {
        if (!this.visited.has(link) && !this.queue.includes(link)) {
          this.queue.push(link);
        }
      }
    }

    this.logger.info(`Crawl complete: processed ${processed} files`);
    return this.contents;
  }

  /**
   * Get all discovered files (visited during crawl)
   */
  getDiscoveredFiles(): string[] {
    return Array.from(this.visited);
  }
}
